# Generated by Django 5.2.7 on 2025-10-03 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspaceinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('developer', 'Developer'), ('viewer', 'Viewer')], max_length=20),
        ),
    ]
